name: 'Skeleton Builder'
author: 'Djamil Legato'
branding:
  icon: 'package'
  color: 'purple'
description: Creates fully functional Grav skeleton packages that include all the necessary dependencies
inputs:
  version:
    description: 'Which Grav version should be used (defaults to latest stable)'
    required: true
    default: 'latest'
  adminPlugin:
    description: 'Create also a package copy with the Admin Plugin installed'
    required: false
    default: true
runs:
  using: 'docker'
  image: Dockerfile
  args:
    - ${{ inputs.version }}
    - ${{ inputs.adminPlugin }}